export const newSeason = [
  {
    id: 1,
    name: 'Barbarians',
    thumbnail: require('../assets/images/series/barbarians/barbarians_cover.jpg'),
    details: {
      image: require('../assets/images/series/barbarians/barbarians.jpg'),
      age: '16+',
      genre: 'Drama',
      ratings: 7.2,
      season: 'TEMPORADA 1',
      currentEpisode: 'T1 : E1 "Episódio 1 : Vikings"',
      runningTime: '45m',
      progress: '0%',
    },
  },
  {
    id: 2,
    name: 'Bridgerton',
    thumbnail: require('../assets/images/series/bridgerton/bridgerton_cover.jpg'),
    details: {
      image: require('../assets/images/series/bridgerton/bridgerton.jpg'),
      age: '18+',
      genre: 'Romance',
      ratings: 7.3,
      season: 'TEMPORADA 1',
      currentEpisode: 'T1 : E6 "Episódio 6 : Swish"',
      runningTime: '45m',
      progress: '50%',
    },
  },
  {
    id: 3,
    name: 'Money Heist',
    thumbnail: require('../assets/images/series/money_heist/money_heist_cover.jpg'),
    details: {
      image: require('../assets/images/series/money_heist/money_heist.jpg'),
      age: '16+',
      genre: 'Crime',
      ratings: 8.3,
      season: 'TEMPORADA 1',
      currentEpisode: 'T1 : E15 "Episódio 15 : Bella ciao"',
      runningTime: '45m',
      progress: '50%',
    },
  },
  {
    id: 4,
    name: 'Salvation',
    thumbnail: require('../assets/images/series/salvation/salvation_cover.jpg'),
    details: {
      image: require('../assets/images/series/salvation/salvation.jpg'),
      age: '13+',
      genre: 'Sci-Fi',
      ratings: 7.0,
      season: 'TEMPORADA 1',
      currentEpisode: 'T1 : E1 "Episódio 1 : Pilot"',
      runningTime: '45m',
      progress: '0%',
    },
  },
];

export const continueWatching = [
  {
    id: 1,
    name: 'Prison Break',
    thumbnail: require('../assets/images/series/prison_break/prison_break_cover.jpg'),
    overallProgress: '20%',
    details: {
      image: require('../assets/images/series/prison_break/prison_break.webp'),
      age: '16+',
      genre: 'Ação',
      ratings: 8.3,
      season: 'TEMPORADA 1',
      currentEpisode: 'T1 : E8 "Episódio 8 : The Old Head"',
      runningTime: '45m',
      progress: '50%',
    },
  },
  {
    id: 2,
    name: 'House of Cards',
    thumbnail: require('../assets/images/series/house_of_cards/house_of_cards_cover.jpg'),
    overallProgress: '50%',
    details: {
      image: require('../assets/images/series/house_of_cards/house_of_cards.jpg'),
      age: '16+',
      genre: 'Drama Político',
      ratings: 8.7,
      season: 'TEMPORADA 1',
      currentEpisode: 'T4 : E1 "Chapter 40"',
      runningTime: '45m',
      progress: '50%',
    },
  },
  {
    id: 3,
    name: 'Bridgerton',
    thumbnail: require('../assets/images/series/bridgerton/bridgerton_cover.jpg'),
    overallProgress: '70%',
    details: {
      image: require('../assets/images/series/bridgerton/bridgerton.jpg'),
      age: '18+',
      genre: 'Romance',
      ratings: 7.3,
      season: 'TEMPORADA 1',
      currentEpisode: 'T1 : E6 "Episódio 6 : Swish"',
      runningTime: '45m',
      progress: '50%',
    },
  },
  {
    id: 4,
    name: 'Money Heist',
    thumbnail: require('../assets/images/series/money_heist/money_heist_cover.jpg'),
    overallProgress: '40%',
    details: {
      image: require('../assets/images/series/money_heist/money_heist.jpg'),
      age: '16+',
      genre: 'Crime',
      ratings: 8.3,
      season: 'TEMPORADA 1',
      currentEpisode: 'T1 : E15 "Episódio 15 : Bella ciao"',
      runningTime: '45m',
      progress: '50%',
    },
  },
];

const dummyData = { newSeason, continueWatching };

export default dummyData;
